spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/**
#         for all urls
#         - Path=/**
#         for single rest controller
#         - Path=/user/**
#         multipule urls for specific controlers
#         - Path=/hotel/**,/staffe/**

server:
  port: 5002

# spring:
#   application:
#     name: API-GATEWAY


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://3.7.18.180:5000/eureka/
