# EQIPPED_DEFAULT_SERVICE

# port
server:
  port: 4999

#eureka server config
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#       defaultZone: http://3.7.18.180:5000/eureka/ # for codea2z
      defaultZone: http://44.210.146.251:5000/eureka/ # for eqipped
 
#spring config  
# spring:
#   application:
#     name: EQIPPED_DEFAULT_SERVICE
#   data:
#     mongodb:
#       uri: mongodb://localhost:27017
#       database: microservicereatingservice
