# EQIPPED_API_GATEWAY configuration file

server:
  port: 5002

#eureka server config
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5000/eureka  
 
#spring config  
spring:
  application:
    name: EQIPPED_API_GATEWAY
  cloud:
    gateway:
      routes:
      - id: EQIPPED_DEFAULT_SERVICE
        uri: lb://EQIPPED_DEFAULT_SERVICE
        predicates:
        - Path=/user/**
        
#       - id: HOTAL-SERVICE
#         uri: lb://HOTAL-SERVICE
#         predicates:
#         - Path=/hotel/**
        # for all urls
        #- Path=/**
        # multipule urls for specific controlers
        #- Path=/hotel/**,/staffe/**
        
#       - id: RATING-SERVICE
#         uri: lb://RATING-SERVICE
#         predicates:
#         - Path=/rating/**
        
        
