# spring:
#   cloud:
#     gateway:
#       routes:
#       - id: USER-SERVICE
#         uri: lb://USER-SERVICE
#         predicates:
#         - Path=/user/**

server:
  port: 5002

spring:
  application:
    name: API-GATEWAY


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5000/eureka/
