# Eqipped product Service
server:
  port: 5005

# Eureka start
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://13.233.173.112:5000/eureka/ # personal for eqipped
      # defaultZone: http://3.7.18.180:5000/eureka/ # for codea2z
      # defaultZone: http://44.210.146.251:5000/eureka/ # for eqipped
# Eureka End
project:
  image: https://eqipped.com/image/
#   image: http://3.6.36.232/image/
#   upload: D:\\eqipped\\eqipped_image
  upload: /var/www/html/image

# Spring Start
spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://admin:gsk3E1ZwjWwgqAoC@cluster0.9xkoq.mongodb.net/
      database: eqipped_new
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

#   config:
#     import: optional:configserver:http://localhost:5001

  mail:
    host: smtp.gmail.com
    port: 587    
    username: amankumar19990923@gmail.com
    password: cbcxjmkitakippqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# Spring End

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


# Start Circuit Breakers through resilience4j server (if another service or server has down then it will return our circiut breakers methods)

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

# Retry Server through resilience4j server (if server is trying multipule time to connect to another server of another server is down then it will return to our methods)
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s

# Rate Limiter
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 1000
        timeout-duration: 2s
