# EQIPPED_USER_SERVICE configuration file

# port
server:
  port: 5003

#eureka server config
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5000/eureka  
 
#spring config  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservicereatingservice
